server:
  port: 8080
spring:
  datasource:
    username: root  # 更标准的属性名
    password: 123   # 建议使用环境变量或加密
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.66.169.95:3306/ape-frame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      filters: stat,wall,slf4j  # 添加过滤器配置，启用SQL监控必需
      stat-view-servlet:  #进行配置druid中的监控
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:     #进行配置sql的拦截器
        stat:
          enabled: true    # 注意这里是enabled而不是enable
          log-slow-sql: true   #开启慢查询的监控
          slow-sql-millis: 2000
        wall:  #SQL防火墙的配置
          enabled: true
        web:
          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  redis:
    host: 100.66.169.95
    port: 6379
    database: 0
    password: 123456
#Spring Boot 支持两种主流 Redis 客户端：
    #
    #Jedis
    #
    #Lettuce
    #
    #其中，Lettuce 是基于 Netty 的异步非阻塞客户端，相比 Jedis（同步阻塞），在高并发场景下性能更好，并且线程安全，推荐使用。
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
swagger:
  base-package: com.qiangi
  title: ape-frame
  contact-name: qiangi
  contact-url: 地址
  email: jichi@163.com
  version: 1.0
  description: 从0到1 开箱即用脚手架
sql:     #进行配置是否进行显示SQL语句中的参数拦截器
  beauty:
    show: true


mybatis-plus:  #进行定义数据库中的逻辑删除,进行标注之后调用mybatis-plus的删除方法是进行逻辑删除
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  config: classpath:log4j2-spring.xml
log:
  aspect:
    enable: true